# Generated by Django 4.1.2 on 2022-11-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nota", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="nota"),
        ),
    ]
