# Generated by Django 4.1.2 on 2022-11-24 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proceso',
            old_name='last_name',
            new_name='tipe',
        ),
    ]
